using UnityEngine;
using UnityEngine.UI;
using TMPro; // Nếu dùng TextMeshPro
using System.Collections.Generic;
using AnomalySystem;

namespace GameUI
{
    public class InventoryUI : MonoBehaviour
    {
        [Header("Left Panel - Description")]
        [Tooltip("Text hiển thị tên vật phẩm")]
        public TextMeshProUGUI itemNameText;
        [Tooltip("Text hiển thị mô tả chi tiết")]
        public TextMeshProUGUI itemDescriptionText;

        [Header("Right Panel - Slots")]
        [Tooltip("Transform chứa Grid Layout Group (nơi sinh ra các ô)")]
        public Transform slotsParent;
        [Tooltip("Prefab của ô vật phẩm (đã gắn script InventorySlot)")]
        public GameObject slotPrefab;

        private InventorySlot currentSelectedSlot;
        private Button actionButton;
        private TextMeshProUGUI actionButtonText;

        private void Start()
        {
            FindOrCreateActionButton();
        }

        private void OnEnable()
        {
            FindOrCreateActionButton();
            RefreshUI();
        }

        [Tooltip("Tổng số ô trong túi đồ (bao gồm cả ô trống)")]
        public int maxSlots = 16;

        public void RefreshUI()
        {
            // 1. Clear thông tin bên trái
            ClearDescription();
            currentSelectedSlot = null;

            if (InventoryManager.Instance == null) return;

            // 2. Tự động sinh thêm các ô đồ (slots) nếu trong slotsParent chưa đủ số lượng maxSlots
            if (slotsParent != null && slotPrefab != null)
            {
                InventorySlot[] existingSlots = slotsParent.GetComponentsInChildren<InventorySlot>(true);
                int needed = maxSlots - existingSlots.Length;
                
                for (int i = 0; i < needed; i++)
                {
                    GameObject newSlotGO = Instantiate(slotPrefab, slotsParent);
                    newSlotGO.name = $"Slot_AutoGenerated_{existingSlots.Length + i + 1}";
                }
            }
            
            List<string> items = InventoryManager.Instance.inventoryList;

            // 3. Tìm tất cả các ô đồ đang có trong slotsParent
            InventorySlot[] allSlots = slotsParent.GetComponentsInChildren<InventorySlot>(true);

            // 4. Đổ dữ liệu vật phẩm vào các ô đã tạo sẵn
            for (int i = 0; i < allSlots.Length; i++)
            {
                // Chỉ xử lý tối đa maxSlots để tránh tràn giao diện
                if (i >= maxSlots)
                {
                    allSlots[i].gameObject.SetActive(false);
                    continue;
                }

                allSlots[i].gameObject.SetActive(true);

                if (i < items.Count)
                {
                    // Nếu người chơi có đồ ở vị trí i, lấy dữ liệu và hiển thị
                    ItemData data = InventoryManager.Instance.GetItemData(items[i]);
                    allSlots[i].Setup(data, this);
                }
                else
                {
                    // Ô trống, giấu Icon đi
                    allSlots[i].Setup(null, this);
                }
            }
        }

        // Hàm được gọi từ InventorySlot khi người dùng click vào
        public void OnSlotSelected(InventorySlot slot, ItemData data)
        {
            // Tắt highlight của slot cũ (nếu có)
            if (currentSelectedSlot != null)
            {
                currentSelectedSlot.SetHighlight(false);
            }

            // Bật highlight cho slot mới
            currentSelectedSlot = slot;
            currentSelectedSlot.SetHighlight(true);

            // Cập nhật text bên trái
            if (itemNameText != null) itemNameText.text = data.itemName;
            if (itemDescriptionText != null) itemDescriptionText.text = data.itemDescription;

            // Xử lý nút Trang bị cho Gấu Bông Phát Sáng
            if (actionButton != null)
            {
                if (data.itemID == "TeddyBear")
                {
                    actionButton.gameObject.SetActive(true);
                    if (actionButtonText != null)
                    {
                        actionButtonText.text = InventoryManager.Instance.IsTeddyBearEquipped ? "Tháo trang bị" : "Trang bị";
                    }
                }
                else
                {
                    actionButton.gameObject.SetActive(false);
                }
            }
        }

        private void OnActionButtonClicked()
        {
            if (currentSelectedSlot == null || currentSelectedSlot.GetItem() == null) return;
            ItemData data = currentSelectedSlot.GetItem();

            if (data.itemID == "TeddyBear" && InventoryManager.Instance != null)
            {
                bool isEquipped = InventoryManager.Instance.IsTeddyBearEquipped;
                InventoryManager.Instance.SetTeddyBearEquipped(!isEquipped);

                if (actionButtonText != null)
                {
                    actionButtonText.text = !isEquipped ? "Tháo trang bị" : "Trang bị";
                }
            }
        }

        private void FindOrCreateActionButton()
        {
            if (actionButton != null) return;

            // Thử tìm nút có sẵn trong Hierarchy
            var btn = transform.Find("LeftPanel/ActionButton") ?? transform.Find("ActionButton");
            if (btn == null)
            {
                foreach (var b in GetComponentsInChildren<Button>(true))
                {
                    if (b.gameObject.name.Contains("Action") || b.gameObject.name.Contains("Equip") || b.gameObject.name.Contains("Use"))
                    {
                        actionButton = b;
                        actionButtonText = b.GetComponentInChildren<TextMeshProUGUI>();
                        break;
                    }
                }
            }
            else
            {
                actionButton = btn.GetComponent<Button>();
                actionButtonText = btn.GetComponentInChildren<TextMeshProUGUI>();
            }

            // Nếu không tìm thấy, tự tạo động tại runtime một nút cực kỳ đẹp mắt
            if (actionButton == null && itemNameText != null)
            {
                Transform parentPanel = itemNameText.transform.parent;
                GameObject btnGO = new GameObject("ActionButton_AutoGenerated");
                btnGO.transform.SetParent(parentPanel, false);

                Image img = btnGO.AddComponent<Image>();
                img.color = new Color(0.12f, 0.12f, 0.15f, 0.95f); // Nền xám đen mờ sang trọng

                actionButton = btnGO.AddComponent<Button>();

                GameObject txtGO = new GameObject("ButtonText");
                txtGO.transform.SetParent(btnGO.transform, false);
                actionButtonText = txtGO.AddComponent<TextMeshProUGUI>();
                actionButtonText.fontSize = 20;
                actionButtonText.alignment = TextAlignmentOptions.Center;
                actionButtonText.color = Color.white;
                actionButtonText.text = "Trang bị";

                // Kích thước của nút ở dưới bảng mô tả
                RectTransform btnRT = btnGO.GetComponent<RectTransform>();
                btnRT.anchorMin = new Vector2(0.1f, 0.05f);
                btnRT.anchorMax = new Vector2(0.9f, 0.18f);
                btnRT.offsetMin = btnRT.offsetMax = Vector2.zero;

                RectTransform txtRT = txtGO.GetComponent<RectTransform>();
                txtRT.anchorMin = Vector2.zero;
                txtRT.anchorMax = Vector2.one;
                txtRT.offsetMin = txtRT.offsetMax = Vector2.zero;

                ColorBlock colors = actionButton.colors;
                colors.normalColor = new Color(0.12f, 0.12f, 0.15f, 0.95f);
                colors.highlightedColor = new Color(0.25f, 0.25f, 0.3f, 1f);
                colors.pressedColor = new Color(0.08f, 0.08f, 0.1f, 1f);
                actionButton.colors = colors;
            }

            if (actionButton != null)
            {
                actionButton.onClick.RemoveAllListeners();
                actionButton.onClick.AddListener(OnActionButtonClicked);
                actionButton.gameObject.SetActive(false); // Mặc định ẩn
            }
        }

        private void ClearDescription()
        {
            if (itemNameText != null) itemNameText.text = "Chọn vật phẩm";
            if (itemDescriptionText != null) itemDescriptionText.text = "";
            if (actionButton != null) actionButton.gameObject.SetActive(false);
        }
    }
}
