using UnityEngine;
using System.Collections.Generic;

namespace AnomalySystem
{
    public class InventoryManager : MonoBehaviour
    {
        private static InventoryManager _instance;
        public static InventoryManager Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = FindAnyObjectByType<InventoryManager>();
                    if (_instance == null)
                    {
                        GameObject go = new GameObject("InventoryManager_AutoGenerated");
                        _instance = go.AddComponent<InventoryManager>();
                        Debug.Log("[InventoryManager] Tự động sinh Manager tại runtime để phục vụ kiểm thử ở scene bất kỳ!");
                    }
                }
                return _instance;
            }
        }

        public List<string> inventoryList = new List<string>();
        
        [Header("Item Database")]
        [Tooltip("Kéo thả tất cả các ScriptableObject ItemData vào đây")]
        public List<ItemData> itemDatabase = new List<ItemData>();

        public static event System.Action OnEquippedStateChanged;

        public bool IsTeddyBearEquipped
        {
            get => PlayerPrefs.GetInt("IsTeddyBearEquipped", 0) == 1;
            private set
            {
                PlayerPrefs.SetInt("IsTeddyBearEquipped", value ? 1 : 0);
                PlayerPrefs.Save();
            }
        }

        public void SetTeddyBearEquipped(bool equipped)
        {
            IsTeddyBearEquipped = equipped;
            OnEquippedStateChanged?.Invoke();
        }

        private void Awake()
        {
            if (_instance == null)
            {
                _instance = this;
                DontDestroyOnLoad(gameObject);
            }
            else if (_instance != this)
            {
                Destroy(gameObject);
                return;
            }
            
            PopulateDatabaseFromResources();
            LoadInventory();
        }

        private void PopulateDatabaseFromResources()
        {
            if (itemDatabase == null)
            {
                itemDatabase = new List<ItemData>();
            }

            // Tự động quét và nạp các ItemData từ thư mục Resources/Items
            ItemData[] resourcesItems = Resources.LoadAll<ItemData>("Items");
            foreach (var item in resourcesItems)
            {
                if (item != null)
                {
                    // Tránh nạp trùng lặp
                    bool exists = false;
                    foreach (var dbItem in itemDatabase)
                    {
                        if (dbItem != null && dbItem.itemID == item.itemID)
                        {
                            exists = true;
                            break;
                        }
                    }
                    if (!exists)
                    {
                        itemDatabase.Add(item);
                    }
                }
            }

            // Quét thêm ở gốc Resources đề phòng
            ItemData[] rootItems = Resources.LoadAll<ItemData>("");
            foreach (var item in rootItems)
            {
                if (item != null)
                {
                    bool exists = false;
                    foreach (var dbItem in itemDatabase)
                    {
                        if (dbItem != null && dbItem.itemID == item.itemID)
                        {
                            exists = true;
                            break;
                        }
                    }
                    if (!exists)
                    {
                        itemDatabase.Add(item);
                    }
                }
            }

            Debug.Log($"[InventoryManager] Tự động tải thành công {itemDatabase.Count} vật phẩm từ Resources!");
        }

        public void AddItem(string itemID)
        {
            if (!inventoryList.Contains(itemID))
            {
                inventoryList.Add(itemID);
                SaveInventory();
                Debug.Log("[Inventory] Đã thêm vật phẩm: " + itemID);
            }
        }

        public bool HasItem(string itemID)
        {
            return inventoryList.Contains(itemID);
        }

        public void RemoveItem(string itemID)
        {
            if (inventoryList.Contains(itemID))
            {
                inventoryList.Remove(itemID);
                SaveInventory();
            }
        }

        public void ClearInventory()
        {
            inventoryList.Clear();
            SaveInventory();
        }

        private void SaveInventory()
        {
            string data = string.Join(",", inventoryList);
            PlayerPrefs.SetString("SavedInventory", data);
            PlayerPrefs.Save();
        }

        public void LoadInventory()
        {
            string data = PlayerPrefs.GetString("SavedInventory", "");
            inventoryList = new List<string>();
            if (!string.IsNullOrEmpty(data))
            {
                inventoryList.AddRange(data.Split(','));
            }
        }

        // Lấy thông tin chi tiết của vật phẩm từ ID
        public ItemData GetItemData(string itemID)
        {
            if (itemDatabase == null || itemDatabase.Count == 0)
            {
                PopulateDatabaseFromResources();
            }

            foreach (var item in itemDatabase)
            {
                if (item != null && item.itemID == itemID)
                {
                    return item;
                }
            }

            // Tự động sinh dữ liệu tại runtime nếu chưa được tạo/gán trong Editor
            ItemData fallbackItem = ScriptableObject.CreateInstance<ItemData>();
            fallbackItem.itemID = itemID;

            switch (itemID)
            {
                case "Book":
                    fallbackItem.itemName = "Sổ Nhật Ký";
                    fallbackItem.itemDescription = "Quyển sổ cũ kỹ ghi lại hành trình của một người đi trước. Chứa đựng nhiều manh mối quan trọng về quy luật vòng lặp.";
                    break;
                case "TornPage_Room1":
                    fallbackItem.itemName = "Mảnh Giấy Xé Rách";
                    fallbackItem.itemDescription = "Mảnh giấy cảnh báo rằng cánh cửa kia không phải lối ra, mà là một vòng lặp. Cần phải quan sát thật kỹ sự thay đổi khi bước qua.";
                    break;
                case "BibleNote_Room3":
                    fallbackItem.itemName = "Trang Kinh Thánh";
                    fallbackItem.itemDescription = "\"Sự sáng chiếu trong tối tăm, và tối tăm không tiếp nhận sự sáng.\" Nguồn sáng chính là vũ khí duy nhất để sinh tồn.";
                    break;
                case "MannequinNote_Room4":
                    fallbackItem.itemName = "Tờ Giấy Cảnh Báo";
                    fallbackItem.itemDescription = "Ghi chú khẩn thiết từ mười hai người đi trước: hãy chạy thật nhanh qua cánh cửa cuối cùng và TUYỆT ĐỐI ĐỪNG NHÌN LẠI!";
                    break;
                case "TeddyBear":
                    fallbackItem.itemName = "Gấu Bông Phát Sáng";
                    fallbackItem.itemDescription = "Con gấu bông kỳ bí tỏa ra ánh sáng ấm áp. Trang bị con gấu để tạo ra một lá chắn ánh sáng bảo vệ bản thân và xua đuổi các linh hồn tà ác xung quanh.";
                    break;
                default:
                    fallbackItem.itemName = itemID;
                    fallbackItem.itemDescription = "Một vật phẩm thu thập được trong quá trình chơi.";
                    break;
            }

            return fallbackItem;
        }

    }
}
